import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import FloatingButtons from "@/components/FloatingButtons";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

/* ------------------------------------------------------------------ */
/*  Viewport — exported separately per Next.js 14+ best practice      */
/* ------------------------------------------------------------------ */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#1B2A6B",
};

/* ------------------------------------------------------------------ */
/*  Metadata — comprehensive SEO configuration                        */
/* ------------------------------------------------------------------ */
export const metadata: Metadata = {
  metadataBase: new URL("https://masshvac.net"),

  /* ---- Title (under 60 chars) ---- */
  title: {
    default: "Mass HVAC Inc | Heating & Cooling in Massachusetts",
    template: "%s | Mass HVAC Inc",
  },

  /* ---- Description (under 160 chars, CTA front-loaded) ---- */
  description:
    "Top-rated HVAC contractor in Massachusetts. 24/7 heating & cooling service. Licensed & insured. Call (508) 740-4113 for a free estimate.",

  /* ---- Keywords (trimmed to core terms — Google ignores this tag) ---- */
  keywords: [
    "HVAC Massachusetts",
    "HVAC contractor MA",
    "heating and cooling Massachusetts",
    "furnace repair MA",
    "AC installation Massachusetts",
    "ductless mini-split MA",
    "heat pump installation MA",
    "HVAC maintenance Massachusetts",
    "emergency HVAC service MA",
    "Mass HVAC Inc",
  ],

  /* ---- Open Graph (image auto-generated by opengraph-image.tsx) ---- */
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "Mass HVAC Inc",
    title: "Mass HVAC Inc | Heating & Cooling in Massachusetts",
    description:
      "Top-rated HVAC contractor in MA. Heating, AC, mini-splits & more. 24/7 emergency service. Licensed & insured. Call (508) 740-4113.",
    url: "https://masshvac.net",
  },

  /* ---- Twitter / X (image auto-generated by twitter-image.tsx) ---- */
  twitter: {
    card: "summary_large_image",
    title: "Mass HVAC Inc | #1 Heating & Cooling in Massachusetts",
    description:
      "Professional HVAC services across Massachusetts. Heating, AC, mini-splits, heat pumps & more. 24/7 emergency service. 5-star Google rated. Call (508) 740-4113 for a free estimate.",
  },

  /* ---- Robots / Crawling ---- */
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  /* ---- Alternates (canonical set per-page, not globally) ---- */
  alternates: {
    languages: {
      "en-US": "https://masshvac.net",
    },
  },

  /* ---- Icons & Manifest ---- */
  icons: {
    icon: [
      { url: "/favicon.png", type: "image/png" },
    ],
    apple: [
      { url: "/favicon.png", type: "image/png" },
    ],
  },

  /* ---- Category ---- */
  category: "HVAC Services",

  /* ---- Verification — uncomment when verified ---- */
  // verification: {
  //   google: "YOUR_GOOGLE_SEARCH_CONSOLE_CODE",
  //   yandex: "YOUR_YANDEX_CODE",
  //   other: { "msvalidate.01": "YOUR_BING_CODE" },
  // },

  /* ---- Other SEO meta ---- */
  other: {
    "geo.region": "US-MA",
    "geo.placename": "Massachusetts",
    "geo.position": "42.2626;-71.8023",
    "ICBM": "42.2626, -71.8023",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "format-detection": "telephone=yes",
    "mobile-web-app-capable": "yes",
  },
};

/* ------------------------------------------------------------------ */
/*  JSON-LD Structured Data (Organization + LocalBusiness + Service)   */
/* ------------------------------------------------------------------ */
function OrganizationJsonLd() {
  const organizationSchema = {
    "@context": "https://schema.org",
    "@type": "HVACBusiness",
    "@id": "https://masshvac.net/#organization",
    name: "Mass HVAC Inc",
    alternateName: ["Mass HVAC", "MASS HVAC INC"],
    url: "https://masshvac.net",
    logo: "https://masshvac.net/logo.png",
    image:
      "https://masshvac.net/logo.png",
    description:
      "Mass HVAC Inc is Massachusetts' top-rated HVAC contractor providing heating installation & repair, air conditioning, ductless mini-splits, heat pumps, maintenance, and indoor air quality services. 24/7 emergency service across MetroWest, Worcester & Greater Boston.",
    telephone: "+1-508-740-4113",
    email: "info@masshvac.net",
    foundingDate: "2020",
    priceRange: "$$",
    currenciesAccepted: "USD",
    paymentAccepted: "Cash, Credit Card, Check, Financing",
    areaServed: [
      {
        "@type": "State",
        name: "Massachusetts",
        sameAs: "https://en.wikipedia.org/wiki/Massachusetts",
      },
      {
        "@type": "City",
        name: "Framingham",
        containedInPlace: { "@type": "State", name: "Massachusetts" },
      },
      {
        "@type": "City",
        name: "Worcester",
        containedInPlace: { "@type": "State", name: "Massachusetts" },
      },
      {
        "@type": "City",
        name: "Natick",
        containedInPlace: { "@type": "State", name: "Massachusetts" },
      },
      {
        "@type": "City",
        name: "Marlborough",
        containedInPlace: { "@type": "State", name: "Massachusetts" },
      },
      {
        "@type": "City",
        name: "Milford",
        containedInPlace: { "@type": "State", name: "Massachusetts" },
      },
      {
        "@type": "City",
        name: "Newton",
        containedInPlace: { "@type": "State", name: "Massachusetts" },
      },
      {
        "@type": "City",
        name: "Wellesley",
        containedInPlace: { "@type": "State", name: "Massachusetts" },
      },
      {
        "@type": "City",
        name: "Hopkinton",
        containedInPlace: { "@type": "State", name: "Massachusetts" },
      },
    ],
    address: {
      "@type": "PostalAddress",
      addressLocality: "Milford",
      addressRegion: "MA",
      postalCode: "01757",
      addressCountry: "US",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: 42.2626,
      longitude: -71.8023,
    },
    openingHoursSpecification: [
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: [
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
        ],
        opens: "07:00",
        closes: "20:00",
      },
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: ["Saturday"],
        opens: "08:00",
        closes: "17:00",
      },
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: ["Sunday"],
        opens: "00:00",
        closes: "23:59",
        description: "Emergency service available 24/7",
      },
    ],
    knowsAbout: [
      "HVAC Installation",
      "Furnace Repair",
      "Boiler Repair",
      "Air Conditioning Installation",
      "Air Conditioning Repair",
      "Heat Pump Installation",
      "Ductless Mini-Split Systems",
      "HVAC Maintenance",
      "Indoor Air Quality",
      "Air Duct Cleaning",
      "Thermostat Installation",
      "Emergency Heating Service",
      "Energy Efficiency",
      "Mass Save Rebates",
    ],
    sameAs: [
      "https://www.facebook.com/masshvacinc",
      "https://www.instagram.com/masshvacinc",
      "https://www.google.com/maps/place/Mass+HVAC+Inc",
    ],
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: "HVAC Services",
      itemListElement: [
        {
          "@type": "OfferCatalog",
          name: "Heating Services",
          itemListElement: [
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Heating Installation & Repair",
                description:
                  "Expert furnace and boiler installation, repair, and replacement services across Massachusetts.",
                url: "https://masshvac.net/services/heating-installation-repair",
              },
            },
          ],
        },
        {
          "@type": "OfferCatalog",
          name: "Cooling Services",
          itemListElement: [
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Air Conditioning Installation & Repair",
                description:
                  "Professional AC installation, repair, and maintenance in Massachusetts.",
                url: "https://masshvac.net/services/air-conditioning-installation-repair",
              },
            },
          ],
        },
        {
          "@type": "OfferCatalog",
          name: "Mini-Split Services",
          itemListElement: [
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Ductless Mini-Split Installation",
                description:
                  "Ductless mini-split heat pump installation and repair for energy-efficient heating and cooling.",
                url: "https://masshvac.net/services/heat-pumps-ductless-mini-splits",
              },
            },
          ],
        },
        {
          "@type": "OfferCatalog",
          name: "Maintenance",
          itemListElement: [
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "HVAC Maintenance & Tune-Ups",
                description:
                  "Preventive HVAC maintenance plans and seasonal tune-ups to keep your system running efficiently.",
                url: "https://masshvac.net/services/hvac-maintenance-tune-ups",
              },
            },
          ],
        },
        {
          "@type": "OfferCatalog",
          name: "Indoor Air Quality",
          itemListElement: [
            {
              "@type": "Offer",
              itemOffered: {
                "@type": "Service",
                name: "Indoor Air Quality Solutions",
                description:
                  "Air purifiers, humidifiers, dehumidifiers, UV lights, and duct cleaning for healthier indoor air.",
                url: "https://masshvac.net/services/indoor-air-quality",
              },
            },
          ],
        },
      ],
    },
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: "4.9",
      bestRating: "5",
      worstRating: "1",
      ratingCount: "47",
      reviewCount: "38",
    },
  };

  const websiteSchema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": "https://masshvac.net/#website",
    name: "Mass HVAC Inc",
    alternateName: "Mass HVAC",
    url: "https://masshvac.net",
    description:
      "Massachusetts' top-rated HVAC contractor — heating, cooling, mini-splits, maintenance & indoor air quality. 24/7 emergency service. Licensed & insured. Serving 100+ cities across MA.",
    publisher: {
      "@id": "https://masshvac.net/#organization",
    },
    potentialAction: [
      {
        "@type": "CommunicateAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: "tel:+15087404113",
        },
        description: "Call Mass HVAC for a free HVAC estimate",
      },
    ],
    inLanguage: "en-US",
    copyrightYear: new Date().getFullYear(),
    speakable: {
      "@type": "SpeakableSpecification",
      cssSelector: ["h1", "h2", ".faq-answer", "[role='main'] p:first-of-type"],
    },
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(organizationSchema),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(websiteSchema),
        }}
      />
    </>
  );
}

/* ------------------------------------------------------------------ */
/*  Root Layout Component                                              */
/* ------------------------------------------------------------------ */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className={inter.variable}>
      <head>
        {/* Preconnect to critical third-party origins for performance */}
        <link rel="preconnect" href="https://assets.cdn.filesafe.space" />
        <link rel="preconnect" href="https://widgets.leadconnectorhq.com" />
        <link
          rel="dns-prefetch"
          href="https://link.msgsndr.com"
        />
        <link
          rel="dns-prefetch"
          href="https://reputationhub.site"
        />

        {/* Favicon */}
        <link rel="icon" href="/favicon.png" type="image/png" />

        {/* JSON-LD Structured Data */}
        <OrganizationJsonLd />

        {/* Form embed script */}
        <Script
          src="https://link.msgsndr.com/js/form_embed.js"
          strategy="lazyOnload"
        />

        {/* Reviews widget script */}
        <Script
          src="https://reputationhub.site/reputation/assets/review-widget.js"
          strategy="lazyOnload"
        />

        {/* Google Tag Manager — uncomment and replace GTM-XXXXX when ready
        <Script id="gtm" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-XXXXX');`}
        </Script>
        */}
      </head>

      <body className="font-sans antialiased">
        {/* Google Tag Manager noscript — uncomment when GTM is active
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXX"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        */}

        <Header />
        <main id="main-content">{children}</main>
        <Footer />
        <FloatingButtons />

        {/* Chat widget — global, bottom right */}
        <Script
          src="https://widgets.leadconnectorhq.com/loader.js"
          data-resources-url="https://widgets.leadconnectorhq.com/chat-widget/loader.js"
          data-widget-id="693ae35c576271e28f3f6196"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
