import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Mass HVAC Inc Privacy Policy — how we collect, use, share, and protect the personal information of our customers across Massachusetts.",
  alternates: { canonical: "https://masshvac.net/privacy" },
};

export default function PrivacyPolicy() {
  return (
    <LegalPage title="Privacy Policy" lastUpdated="May 1, 2026">
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service operated by <strong>Mass HVAC Inc</strong> (&quot;the
        Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;) and
        tells You about Your privacy rights and how the law protects You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <h2>1. Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <h3>Definitions</h3>
      <ul>
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party.</li>
        <li><strong>Company</strong> refers to Mass HVAC Inc, located in Milford, MA 01757.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: Massachusetts, United States.</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        <li><strong>Website</strong> refers to Mass HVAC Inc, accessible from <a href="https://masshvac.net">masshvac.net</a>.</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
      </ul>

      <h2>2. Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>
      <p><strong>Personal Data</strong></p>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Project type, project location, scope details</li>
        <li>Usage Data</li>
      </ul>

      <p><strong>Usage Data</strong></p>
      <p>
        Usage Data is collected automatically when using the Service. Usage Data
        may include information such as Your Device&apos;s Internet Protocol
        address (e.g. IP address), browser type, browser version, the pages of
        our Service that You visit, the time and date of Your visit, the time
        spent on those pages, unique device identifiers and other diagnostic
        data.
      </p>

      <h3>Tracking Technologies and Cookies</h3>
      <p>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies
        used are beacons, tags, and scripts to collect and track information
        and to improve and analyze Our Service. The technologies We use may
        include:
      </p>
      <ul>
        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company, for example, to count users who have visited those pages or opened an email.</li>
      </ul>

      <h2>3. Use of Your Personal Data</h2>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li><strong>To provide and maintain our Service</strong>, including monitoring usage.</li>
        <li><strong>To manage Your Account</strong>: managing Your registration as a user of the Service.</li>
        <li><strong>For the performance of a contract</strong>: development, compliance and undertaking of the contract for the services You have purchased or of any other contract with Us.</li>
        <li><strong>To contact You</strong>: by email, telephone calls, SMS, or push notifications regarding updates or informative communications related to the functionalities, products or contracted services.</li>
        <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events similar to those that You have already purchased or enquired about (unless You have opted not to receive such information).</li>
        <li><strong>To manage Your requests</strong>: to attend and manage Your requests to Us.</li>
        <li><strong>For business transfers</strong>: We may use Your information to evaluate or conduct a merger, sale, or other transfer.</li>
        <li><strong>For other purposes</strong>: data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service.</li>
      </ul>

      <h2>4. Sharing of Personal Data</h2>
      <p>We may share Your personal information in the following situations:</p>
      <ul>
        <li><strong>With Service Providers</strong>: to monitor and analyze the use of our Service, to contact You (CRM, SMS, email, scheduling).</li>
        <li><strong>For business transfers</strong>: in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</li>
        <li><strong>With Affiliates</strong>: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
        <li><strong>With business partners</strong>: to offer You certain products, services or promotions.</li>
        <li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>
      </ul>
      <p>
        <strong>We do NOT sell Your personal data.</strong> Mobile information
        — including phone numbers and SMS opt-in consent — is not shared,
        sold, rented, or transferred to third parties or affiliates for
        marketing or promotional purposes under any circumstances. See our{" "}
        <a href="/sms-terms">SMS Terms</a> for full details.
      </p>

      <h2>5. SMS Messaging Consent</h2>
      <p>
        By providing Mass HVAC Inc with Your phone number — through the chat
        widget on our Website, a service request form, or verbal consent during
        a phone call — You consent to receive SMS messages from us related to
        Your project, estimate, scheduling, and service updates.
      </p>
      <ul>
        <li>Message frequency varies. Standard message and data rates may apply.</li>
        <li>Reply <code>STOP</code> at any time to opt out. Reply <code>HELP</code> for help.</li>
        <li>Your mobile information stays with Mass HVAC. We do not sell, rent, or share it with third parties or affiliates for their marketing purposes.</li>
      </ul>
      <p>
        Full details are in our <a href="/sms-terms">SMS Terms &amp; Opt-In Methods</a>.
      </p>

      <h2>6. Retention of Your Personal Data</h2>
      <p>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations, resolve disputes, and enforce our legal
        agreements and policies.
      </p>

      <h2>7. Transfer of Your Personal Data</h2>
      <p>
        Your information is processed at the Company&apos;s operating offices
        and in any other places where the parties involved in the processing are
        located. It means that this information may be transferred to — and
        maintained on — computers located outside of Your state, province,
        country or other governmental jurisdiction where the data protection
        laws may differ.
      </p>

      <h2>8. Delete Your Personal Data</h2>
      <p>
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You. Our Service may give You
        the ability to delete certain information about You from within the
        Service. You may also contact Us to request access to, correct, or
        delete any personal information that You have provided to Us.
      </p>

      <h2>9. Disclosure of Your Personal Data</h2>
      <h3>Law enforcement</h3>
      <p>
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities.
      </p>
      <h3>Other legal requirements</h3>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h2>10. Security of Your Personal Data</h2>
      <p>
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </p>

      <h2>11. Children&apos;s Privacy</h2>
      <p>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us.
      </p>

      <h2>12. Links to Other Websites</h2>
      <p>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party&apos;s site. We strongly advise You to review the Privacy
        Policy of every site You visit.
      </p>

      <h2>13. Changes to this Privacy Policy</h2>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page and
        updating the &quot;Last updated&quot; date. You are advised to review
        this Privacy Policy periodically for any changes.
      </p>

      <h2>14. Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul>
        <li>By email: <a href="mailto:info@masshvac.net">info@masshvac.net</a></li>
        <li>By phone: <a href="tel:+15087868755">(508) 786-8755</a></li>
        <li>By visiting this page on our website: <a href="/">masshvac.net</a></li>
        <li>By mail: Mass HVAC Inc, Milford, MA 01757</li>
      </ul>
    </LegalPage>
  );
}
